### ISSUE TITLE
Delay between Program and Read causes failure

### ISSUE THREAD

**Issue by AsternA** [squaresausage/WinbondW25N#1]
Hey Guys,

Ive uploaded the example and it works great so I got to work on it using my own program.
However, I noticed that when I try to program a page (or a couple) [programExecute] and **after a while** read the page (or pages) [pageDataRead and then Read] it reads wrong information.

So I headed back to the example, and between the programExecute and pageDataRead i put in a small - 500 [mS] delay and the problem repeated! 

```
ret = ProgramExecute(0);
#if DEBUG
Serial.print("Program Execute: ");
Serial.println(ret);
#endif
// TODO - Experimental:
delay(500);
// Read the Data back and print it in
ret = pageDataRead(0);
#if DEBUG
Serial.print("Page Data Read: ");
Serial.println(ret);
#endif
```

without the delay(500) i get "Read str EQUALs Write str!", 
WITH the delay - it does NOT equal....
Any ideas why this happens?

Cheers

Almog

**Comment by squaresausage** [comment]
Hi @AsternA , 

Could I see more of the code for context please? The example in the library just prints out the string, it doesnt compare before and after. 

Thank you
Cameron

**Comment by AsternA** [comment]
Hey Cameron,
Sure thing.. here it is...

This is just the sample I took:

```
int init_SPI()
{
 
    // Set pin as the slave select for the digital port
    const int _CS = 19;     // D19 at the variant.cpp
                            // 3, D19 is P0.03 (A5)

    /*
    15,  // D24 is P0.15 (SPI MISO)
    13,  // D25 is P0.13 (SPI MOSI)
    14,  // D26 is P0.14 (SPI SCK ) 
    */
    const int _SCK  = 14;
    const int _MISO = 15;
    const int _MOSI = 13;

    unsigned int address = 0;

    Serial.print("Enter Init SPI....\n");

    pinMode(_CS, OUTPUT);

    SPI.begin();
    SPI.setDataMode(SPI_MODE0);
    SPI.setBitOrder(MSBFIRST);
    SPI.setClockDivider(SPI_CLOCK_DIV16);
    delay(1);

    char* myString = "Hello World from the W25N Flash Chip!";
    char buf[512];
    int ret;

    long timer = millis();

    char buf1[3] = {0x1F, W25N_PROT_REG, 0x87};     // clear prot bits in any case
                                                    // a MUST even if the WP Pin is Attached to the VCC

    // Send data to Prot Register
    digitalWrite(_CS, LOW);                         
    SPI.transfer(buf1, sizeof(buf1));
    digitalWrite(_CS, LOW);

    // Put the String into our Flash buffer,
    // We cant point to the string directly as it is static
    // and the buffer will be modified with the received data
    memcpy(buf, myString, strlen(myString) + 1);

    // Transfer the data we want to program and execute the program command
    ret = loadProgData(0, &buf[0], strlen(myString) + 1);
    Serial.print("Load Program Data: ");
    Serial.println(ret);

    ret = ProgramExecute(0);
    Serial.print("Program Execute: ");
    Serial.println(ret);
                                                                     // here is the problem - if I put a delay it doesn't work.
    // Read the Data back and print it in
    ret = pageDataRead(0);
    Serial.print("Page Data Read: ");
    Serial.println(ret);
    delay(3);                                                                        
    memset(buf, 0x55, sizeof(buf));
    ret = read(0, buf, sizeof(buf));
    Serial.print("Read: ");
    Serial.println(ret);

    Serial.println(buf);
    Serial.print("Time: ");
    Serial.println(millis() - timer);

    if(memcmp(buf,myString,sizeof((myString) )) != 0)     
    {
        ret = 1;
        Serial.print("Read str does NOT equal Write str!!\n");
    }
    else
    {
        ret = 0;
        Serial.print("Read str EQUALS Write str!\n");
    }
}
```

if I change the delay between the pageExecute and pageDataRead functions to something larger, say 500ms... it does not work.

This is strange because I want to write and write and write and only after a long time, read the pages I have written.

Really baffled by this.

Any help is appreciated 

Almog

**Comment by squaresausage** [comment]
My first thought would be that there is a timeout if you call pageDataRead and wait too long to read the data. 

Can I ask why you need to use a delay between these two functions, and not just delay before or after the whole read process? 

Also, if you add a delay to the stock example, without changing anything else, does this still happen? 

Best
Cameron

**Comment by AsternA** [comment]
The problem is, except for the 3 ms delay there is no other delay after calling pageDataRead.
Im calling pageDataRead and immediately calling Read().

The problem happens when I call pageExecute and then WAIT to call pageDataRead...

"Can I ask why you need to use a delay between these two functions, and not just delay before or after the whole read process?"
I want to write lots of data and read it only once after its been filled. In my code the user uses the device and the flash stores the user's data, and I need to read the data only when the device is charging... 

"Also, if you add a delay to the stock example, without changing anything else, does this still happen?"
What I have shown you is taken from the stock example... i have tried it almost 1 to 1 with no success..

Putting a delay AFTER pageExecute causes the pageDataRead and Read functions to read incorrect data.. :(

Almog

**Comment by squaresausage** [comment]
Your code has many many differences, including the lack of any W25N object. Some of these functions (such as programExecute) refer to this object. I don't actually know how this would compile without a W25N object. 

If you can run the stock WriteString.ino file with the only change being the addition of a delay(500); between programExectute and pageDataRead then I can be sure that the problem isn't with any of your code.

**Comment by AsternA** [comment]
You're right, i have removed the object from the script.

but the functions do not specifically require the object as long as they are defined in the proper place (which they are).

The sample code I've shared with you has the function init_SPI().... I have written the following functions (your exact functions) above:
```
int check_WIP(){
  char status = this->getStatusReg(W25N_STAT_REG);
  if(status & 0x01){
    return 1;
  }
  return 0;
}                      

int block_WIP(){
  //Max WIP time is 10ms for block erase so 15 should be max.
  unsigned long tstamp = millis();
  while(this->check_WIP()){
    delay(1);
    if (millis() > tstamp + 15) return 1;
  }
  return 0;
}

void sendData(char* buf, uint32_t len)
{
    SPI.beginTransaction(SPISettings(4000000, MSBFIRST, SPI_MODE0));
    digitalWrite(_CS, LOW);
    SPI.transfer(buf, len);
    digitalWrite(_CS, HIGH);
    SPI.endTransaction();
}

void writeEnable()
{
    char buf[] = {W25N_WRITE_ENABLE};
    sendData(buf, sizeof(buf));
}

int loadProgData(uint16_t columnAdd, char* buf, uint32_t dataLen)
{
    if(columnAdd > (uint32_t)MAX_COLUMN)                return 1;
    if(dataLen > (uint32_t)MAX_COLUMN - columnAdd)      return 1;

    char columnHigh = (columnAdd & 0xFF00) >> 8;
    char columnLow = columnAdd & 0xFF;
    char cmdbuf[3] = {W25N_PROG_DATA_LOAD, columnHigh, columnLow};
    block_WIP();
    writeEnable();
    SPI.beginTransaction(SPISettings(4000000, MSBFIRST, SPI_MODE0));
    digitalWrite(_CS, LOW);
    SPI.transfer(cmdbuf, sizeof(cmdbuf));
    SPI.transfer(buf, dataLen);
    digitalWrite(_CS, HIGH);
    SPI.endTransaction();
    return 0;
}

int ProgramExecute(uint32_t pageAdd)
{
    if(pageAdd > getMaxPage())      return 1;

    char pageHigh = (char)((pageAdd & 0xFF00) >> 8);
    char pageLow = (char)pageAdd;

    writeEnable();
    char buf[4] = {W25N_PROG_EXECUTE, 0x00, pageHigh, pageLow};
    sendData(buf, sizeof(buf));
    return 0;
}

int pageDataRead(uint32_t pageAdd)
{
    if(pageAdd > getMaxPage())      return 1;

    char pageHigh = (char)((pageAdd & 0xFF00) >> 8);
    char pageLow = (char)(pageAdd);
    char buf[4] = {W25N_PAGE_DATA_READ, 0x00, pageHigh, pageLow};
    block_WIP();
    sendData(buf, sizeof(buf));
    return 0;
}

int read(uint16_t columnAdd, char* buf, uint32_t dataLen)
{
    if(columnAdd > (uint32_t)MAX_COLUMN)            return 1;
    if(dataLen > (uint32_t)MAX_COLUMN - columnAdd)  return 1;  
    
    char columnHigh = (columnAdd & 0xFF) >> 8;
    char columnLow = columnAdd & 0xFF;
    char cmdbuf[4] = {W25N_READ, columnHigh, columnLow, 0x00};
    block_WIP();
    SPI.beginTransaction(SPISettings(4000000, MSBFIRST, SPI_MODE0));
    digitalWrite(_CS, LOW);
    SPI.transfer(cmdbuf, sizeof(cmdbuf));
    SPI.transfer(buf, dataLen);
    digitalWrite(_CS, HIGH);
    SPI.endTransaction();
    return 0;
}

```
Writing all that I have to say that I am sorry to have wasted your time... It turns out the chip we are using is TC58CVG2S0HRAIG
from TOSHIBA which is really just WInbond in disguise. 

But since you are here already, if it isn't too much trouble maybe you could compile the WriteString.ino example with the delay(500) and let me know if that works for you?
Would really help me a lot 

Attached is the datasheet for TC58CVG2S0HRAIG which you will see it is using the same #defines as WInbond and well, up to this point even the functions worked the same...

Regards,

Almog
[TC58CVG2S0HxAIx_Rev1.1_2016-11-08.pdf](https://github.com/squaresausage/WinbondW25N/files/5968466/TC58CVG2S0HxAIx_Rev1.1_2016-11-08.pdf)

**Comment by AsternA** [comment]
Hey Cameron, 

Did you have a chance to try putting a large delay between programExecute and pageDataRead? Does everything work well on your end?

Regards,
Almog
