### ISSUE TITLE
Wrong filename in #include ?

### ISSUE THREAD

**Issue by castle055** [squaresausage/WinbondW25N#2]
The first line on the WInbondW25N.cpp file does not name the header file properly. The 'i' is supposed to be uppercase like 'I'.

`#include "WinbondW25N.h"`
should be
`#include "WInbondW25N.h"`

I've had to clone this repo a few sporadic times and this error always takes me a while to debug. I thought I'd better post an issue.

**Comment by squaresausage** [comment]
Ah thank you for that, Ill fix it right away/ Ive only ever tested this library on windows!

**Comment by castle055** [comment]
Oh that makes sense. Thanks for the quick response.
