### ISSUE TITLE
repeated block erase at the same block

### ISSUE THREAD

**Issue by wichlio** [squaresausage/WinbondW25N#3]
Does W25N::bulkErase send multiple unnecessary block erase command to the same block ?
Do we need to send 64 block erase to the same block ?
Thanks.

```
int W25N::bulkErase(){
  int error = 0;
  for(uint32_t i = 0; i < this->getMaxPage(); i++){
    if((error = this->blockErase(i)) != 0) return error;
  }
  return 0;
}
```

**Comment by squaresausage** [comment]
You are completely correct! Thank you for finding this issue, I will fix it shortly.
